package com.example.zago;

public enum Acao {



    CONFIRMARCRIACAOPERSONAGEM, ENTRAR,

    INFOVALOR, INFOFLOAT, INFOBYTE, INFODOUBLE, INFOSHORT, INFONOME, INFOOPERADORIGUAL,INFOINT,INFOOPERADORCONCATENACAO,

    CRIARVARIAVELFORCA, CRIARVARIAVELVIDA, CRIARVARIAVELDEF, CRIARVARIAVELVEL, CRIARMETODOATACAR, CRIARMETODODEFESA, MARIASELECAO,

    PREMIOTUTORIAL,CONFIRMARSELECAO,BOLSA,

    CONFIRMARCRIACAOVARIAVEL,

    JHOSELECAO, OKPREMIACAO, BAUPREMIACAOTUTORIAL, CARTAOTELA, CARTAOJOGADOR,
    TELACRIARPERSONAGEM,TELAMUNDO, TELADETALHE,  TELAGLACIES, TELASILVA, TELAVULCANO, TELASELECAOCAMPEAO,
    TELADESCRICAOARANHA, TELABATALHAMORCEGO, TELADESCRICAOMARIA, TELADESCRICAOJHO,    BATALHAMORCEGO, TELACRIACAO, TELACRIACAOMETODO,
    TELACRIACAOMETODOATACAR, TELACRIACAOMETODODEFENDER, NULL,
    CONFIRMARCRIACAOVARIAVELVIDA, CONFIRMARCRIACAOVARIAVELFORCA, CONFIRMARCRIACAOVARIAVELDEFESA, CONFIRMARCRIACAOVARIAVELVELOCIDADE, CONFIRMARCRIACAOMETODO,
    CONFIRMARCRIACAOMETODOATACAR, CONFIRMARCRIACAOMETODODEFENDER, CONFIRMACAODETALHE, TELASELECAOMETODO, TELACRIACAOVARIAVEL, TELACRIACAOCONCATENACAO, ANTERIOR, PROXIMO, TELACRIACAOLOOP, CARTAOJOGADORVARIAVEL, TELABATALHAARANHA, TELABATALHAJHO, TELABATALHAMARIA, TELABATALHAESQUELETO, TELABATALHAZEFER, TELABATALHAOGROFOGO, TELABATALHAOGROGELO, TELABATALHASUZY, TELABATALHALOBO, INFOOPERADORNOMEMETODO,

}
